### ISSUE TITLE
Pydantic not in requirements, leading to ModuleNotFoundError

### ISSUE THREAD

**Issue by stijn-uva** [centre-for-humanities-computing/stormtrooper#4]
When trying to use the OpenAI classes I get the following exception:

```
Traceback (most recent call last):
  File "script.py", line 119, in <module>
    predictor = OpenAIFewShotClassifier(model_name, temperature=0.2).fit(examples, labels)
  File "/usr/local/lib/python3.10/dist-packages/stormtrooper/error.py", line 20, in __call__
    raise ModuleNotFoundError(self.msg)
ModuleNotFoundError: In order to use OpenAIFewShotClassifier you'll need to install via;

pip install stormtrooper[openai]
```

But the `ModuleNotFoundError` is actually because the `pydantic` module is not installed (in this case), which is used in `openai_async.py`. It is not in the project's requirements so not installed automatically, and the error is misleading, implying that the issue is instead that `stormtrooper[openai]` is absent.

**Comment by x-tabdeveloping** [comment]
Sorry for the inconvenience. I am currently preparing a new large release of the library, as both HuggingFace's and OpenAI's interfaces have significantly changed since last release. I will keep you updated on the status of the release.

**Comment by x-tabdeveloping** [comment]
Version 1.0.0 is out now, this problem should no longer exist :D
