### ISSUE TITLE
GPT models' outputs are not fuzzy matched despite default behavior 

### ISSUE THREAD

**Issue by miscodisco** [centre-for-humanities-computing/stormtrooper#6]
labels from gpt models include misspellings, sentences (i.e., "this text can be classified as xxx"). 

this occurs when doing e.g, `cls = Trooper("gpt4")` and fuzzy matching is true by default.

**Comment by miscodisco** [comment]
this also happens when explicitly setting fuzzy matching as true `cls = Trooper("gpt4", fuzzy_match=True)`
labels are returned with `'`around them and misspelled

**Comment by x-tabdeveloping** [comment]
#7 fixes this <3
